/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define EIS_VERSION "1.3.0"

#define EI_VERSION "1.3.0"

#define HAVE_BASU 0

#define HAVE_LIBELOGIND 0

#define HAVE_LIBEVDEV 1

#define HAVE_LIBSYSTEMD 1

#define HAVE_LIBXKBCOMMON 1

#define HAVE_MEMFD_CREATE 1

#define _GNU_SOURCE 1

